Media upload to Azure Storage
Tietokilta/tikweb-cms pull request #27
Opened 2022-05-29 14:33 UTC by koxanybak

Make the uploaded media to Strapi go to Azure Storage in production.

2022-05-30 20:00 UTC, PurkkaKoodari commented
LGTM. Let's wait for #26 merge and update this before merging.

2022-07-31 18:45 UTC, mrnym commented
Updated to v4 according to: [docs](https://github.com/jakeFeldman/strapi-provider-upload-azure-storage#usage)

2022-07-31 19:22 UTC, PurkkaKoodari requested changes

2022-07-31 19:22 UTC, PurkkaKoodari commented on config/plugins.js
> +  if (env('NODE_ENV') === 'development') return { upload: undefined }
We can move this file to `config/env/production` to avoid a manual check

2022-07-31 19:42 UTC, PurkkaKoodari approved these changes
LGTM

2022-07-31 19:43 UTC, merged